package com.nt.advice;

import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import java.lang.reflect.Method;

import org.springframework.aop.MethodBeforeAdvice;

import com.nt.dto.LoanCustomerInfo;

public class AuditingBeforeAdvice implements MethodBeforeAdvice {
	Writer writer;
	String Msg;

	@Override
	public void before(Method method, Object[] args, Object target) throws Throwable {
		if (method.getName()=="generateLoanId" && ((LoanCustomerInfo)args[0]).getPurpose().equalsIgnoreCase("agri")) {
			Msg = "loan id generated by " + ((LoanCustomerInfo) args[0]).getClerkName();
		} else if (method.getName() == "apporveLoan")
			Msg = "Loan aprroved by " + ((LoanCustomerInfo) args[1]).getManagerName();

		// auditing logic
		writer = new FileWriter("G:/auditing.txt", true);
		writer.write(Msg);
		writer.flush();
		writer.close();
	}
}