#jdbc confgs
spring: 
   datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/godwe1
      username: root
      password: root
      type: org.apache.commons.dbcp2.BasicDataSource
      